apiVersion: sourceplane.io/v1
kind: Intent
metadata:
  name: simple-nextjs

compositions:
  sources:
    - name: stack-tectonic
      kind: oci
      ref: oci://ghcr.io/sourceplane/stack-tectonic:0.11.0

discovery:
  roots:
    - apps
    - infra

environments:
  development: {}
  production: {}
