apiVersion: sourceplane.io/v1
kind: Component

metadata:
  name: identity-portal-chart

spec:
  type: helm-chart
  domain: customer-identity
  subscribe:
    environments:
      - development
      - staging
  inputs:
    chartPath: .
    valuesFile: ../../../deploy/hello-deploy/values.yaml
    releaseName: identity-portal
    helmVersion: v3.15.4
  labels:
    team: platform
    layer: delivery
    domain: identity
    release: identity-portal
  dependsOn:
    - component: identity-portal-values